controller_list:
  - name: fake_robotarm_controller
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_end_effector_controller
    joints:
      - joint_5
initial:  # Define initial robot poses.
  - group: robotarm
    pose: home